# Generated by Django 5.0.2 on 2025-02-11 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='informes/', verbose_name='Archivo PDF')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('precio_compra', models.FloatField(blank=True, null=True)),
                ('precio_venta', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('EA', 'Entrada Almacén'), ('ST', 'Salida a Tienda'), ('AA', 'Ajuste Almacén'), ('AT', 'Ajuste Tienda'), ('V', 'Venta')], default='EA', max_length=2, verbose_name='Tipo de Flujo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('constancia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Constancia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Flujo',
                'verbose_name_plural': 'Flujos',
                'ordering': ['-created_at'],
            },
        ),
    ]
