# Generated by Django 5.0.2 on 2025-02-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujo',
            name='precio',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio de Venta'),
        ),
    ]
